version: 0.0
os: linux
files:
  - source: stocks-app-api/build/libs/stocks-app-api-0.0.1-SNAPSHOT.jar
    destination: /stocks-app-api
  - source: stocks-app-ui/build/libs/stocks-app-ui-0.0.1-SNAPSHOT.jar
    destination: /tmp/ui
hooks:
  # BeforeInstall:
  #   - location: deployment/scripts/beforeInstall.sh
  #     timeout: 300
  #     runas: root
  Install:
    - location: deployment/scripts/install-ui.sh
      timeout: 300
      runas: root
  # AfterInstall:
  #   - location: deployment/scripts/ras.sh
  #     timeout: 300
  #     runas: root
  ApplicationStart:
    - location: deployment/scripts/start.sh
      timeout: 300
  # ApplicationStop:
  #   - location: scripts/stop_server
  #     timeout: 300
  #     runas: root

