version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew clean build

artifacts:
  files:
    - '**/*'
secondary-artifacts:
  ui-artifact:
    files:
      - '*.jar'
    base-directory: 'stocks-app-ui/build/libs'
  api-artifact:
    files:
      - '*.jar'
    base-directory: 'stocks-app-api/build/libs'

cache:
  paths:
    - '.gradle/caches/**/*'
    - '.gradle/wrapper/**/*'
