version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew clean build

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    api:
      base-directory: stocks-app-api/build/libs/
      files: 
        - '*.jar'
    ui:
      base-directory: stocks-app-ui/build/libs/
      files:
        - '*.jar'
cache:
  paths:
    - '.gradle/caches/**/*'
    - '.gradle/wrapper/**/*'
