version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew clean build

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    api:
      files:
        - stocks-app-api/build/libs/*.jar
      name: stocks-app-api-artifact
    ui:
      files:
        - stocks-app-ui/build/libs/*.jar
      name: stocks-app-ui-artifact
cache:
  paths:
    - '.gradle/caches/**/*'
    - '.gradle/wrapper/**/*'
