version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      java: semeru-17
    commands:
      - npm install
  build:
    commands:
      - ./gradlew clean build
artifacts:
  files:
    - '**/*'
