version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew clean build

artifacts:
  files:
    - 'stocks-app-api/build/libs/*.jar'
    - 'stocks-app-ui/build/libs/*.jar'
cache:
  paths:
    - '.gradle/caches/**/*'
    - '.gradle/wrapper/**/*'
